/**
 * Corale — domain model.
 *
 * These types are the contract between the UI and the data layer. The prototype
 * fulfils them from `data/mock.ts`; the production build fulfils them from the
 * NestJS API. Nothing in `src/app` or `src/components` knows which.
 */

export type Role = "admin" | "manager" | "employee";

export type ContractType =
  | "indeterminato"
  | "determinato"
  | "apprendistato"
  | "collaborazione"
  | "stage";

export type EmployeeStatus = "attivo" | "ferie" | "permesso" | "assente";

export type Severity = "good" | "warn" | "crit";

export interface Department {
  id: string;
  name: string;
  /** Manager's employee id. */
  leadId: string;
  headcount: number;
  /** 0–100 composite performance index for the current period. */
  performance: number;
  /** 0–100 attendance rate for the current period. */
  attendance: number;
  /** Monthly labour cost, EUR. */
  monthlyCost: number;
}

export interface Contract {
  type: ContractType;
  /** ISO date. */
  startDate: string;
  /** ISO date, or null for open-ended. */
  endDate: string | null;
  /** Contractual weekly hours. */
  weeklyHours: number;
  /** Gross annual salary, EUR. */
  grossAnnual: number;
  ccnl: string;
  level: string;
}

export interface PerformanceMetric {
  id: string;
  label: string;
  /** Achieved value, in `unit`. */
  value: number;
  /** Target for the period, in `unit`. */
  target: number;
  unit: string;
  /** Weight of this metric in the composite score, 0–1. */
  weight: number;
  /**
   * Direction of improvement. False for metrics where a lower number is the
   * goal (incidents, cycle time, cost per acquisition) — attainment inverts.
   */
  higherIsBetter: boolean;
}

export type DayKind = "presente" | "ferie" | "permesso" | "assenza" | "festivo";

export interface AttendanceDay {
  /** ISO date. */
  date: string;
  kind: DayKind;
  /** Hours worked; 0 for non-working days. */
  hours: number;
  /** HH:mm, null when not applicable. */
  checkIn: string | null;
  checkOut: string | null;
  /** Minutes late on check-in. */
  lateMinutes: number;
}

export interface CompensationLine {
  label: string;
  /** EUR; negative for deductions. */
  amount: number;
  /** Human-readable explanation of the rule that produced this line. */
  rule: string;
}

export interface Compensation {
  /** e.g. "2026-07". */
  period: string;
  baseMonthly: number;
  lines: CompensationLine[];
  grossTotal: number;
}

export interface Employee {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  role: Role;
  position: string;
  departmentId: string;
  managerId: string | null;
  status: EmployeeStatus;
  /** ISO date. */
  hiredOn: string;
  location: string;
  contract: Contract;
  /** 0–100 composite score for the current period. */
  performanceScore: number;
  /** 0–100 attendance rate for the current period. */
  attendanceRate: number;
  metrics: PerformanceMetric[];
  /** Most recent first. */
  attendance: AttendanceDay[];
  compensation: Compensation;
  /** 12 trailing periods of the composite score, oldest first. */
  performanceTrend: number[];
}

/**
 * An observation produced by the analysis layer.
 *
 * In production these come from the AI module: statistical detectors run over
 * the historical series, and the narrative line is generated by Claude from the
 * detector's output — grounded on queried figures, never invented. `evidence`
 * is what the model was given, so every claim stays auditable.
 */
export interface Insight {
  id: string;
  severity: Severity;
  /** The editorial pull-quote. One sentence, present tense. */
  quote: string;
  /** What the reader should do about it. */
  recommendation: string;
  /** Figures the observation is derived from. */
  evidence: { label: string; value: string }[];
  /** Employee or department the observation is about. */
  subject: { kind: "employee" | "department" | "company"; id: string; name: string };
  /** ISO timestamp. */
  generatedAt: string;
}

export interface ActivityEntry {
  id: string;
  /** ISO timestamp. */
  at: string;
  actor: string;
  action: string;
  target: string;
}

export interface CompanyStats {
  headcount: number;
  headcountDelta: number;
  attendanceRate: number;
  attendanceDelta: number;
  performanceAvg: number;
  performanceDelta: number;
  monthlyCost: number;
  monthlyCostDelta: number;
  /** Weekly attendance rate, oldest first — 12 points. */
  attendanceTrend: { label: string; value: number }[];
}

export interface CurrentUser {
  id: string;
  name: string;
  role: Role;
  position: string;
}
